Test_cases
asingh072318/expertiza pull request #2
Opened 2021-10-19 18:12 UTC by sbkrishna123

Please set the title of your pull request in the following format: `[Project id/Independent study/Issue fix/...]. project name`, eg., `E904. Integrating courses and assignments on Expertiza with Moodle`

We suggest you including the below information in your pull request:
- A description of the changes proposed in the pull request.
- @mentions of the person or team responsible for reviewing proposed changes.
---
About Expertiza Bot
- If you have any questions about comments given by the expertiza-bot [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762412918), you could create a comment in your pull request with the format `/dispute [UUID1] [UUID2]` [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762430057) then the professor and TAs will be notified.
- [Here is a video](https://tinyurl.com/internet-bots) about how to communicate to expertiza-bot.

2021-10-19 18:34 UTC, asingh072318 requested changes

2021-10-19 18:34 UTC, asingh072318 commented on spec/controllers/assessment360_controller_spec.rb
> -  describe '#course_student_grade_summary' do
please remove all instances of course_student_grade_summary as we won't be using it.

2021-10-19 18:54 UTC, sbkrishna123 commented on spec/controllers/assessment360_controller_spec.rb
> -  describe '#course_student_grade_summary' do
Hey, it has been removed. Hence its in Red

2021-10-20 03:23 UTC, asingh072318 approved these changes

2021-10-20 03:23 UTC, merged